app = "kali-fly"

primary_region = "cdg"

[build]

[env]
  FLY_PROCESS_GROUP = "app"

[[services]]
  internal_port = 22
  protocol = "tcp"

  [[services.ports]]
    port = 22

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"