app = "kali-fly"

[build]

[env]
  HOSTNAME = "fly.io"

[[services]]
  internal_port = 22
  protocol = "tcp"

  [[services.ports]]
    port = 22

  [[services.tcp_checks]]
    interval = "10s"
    timeout = "2s"